---
- name: Create a temporary file to store users which were just created by Ansible
  shell: echo -n "" > /tmp/ansible-new-users.txt
  changed_when: false

- name: Search for new users
  shell: grep "^{{item.username}}:!:" /etc/shadow | sed "s/:.*//" >> /tmp/ansible-new-users.txt
  with_items: users
  changed_when: false

- name: Read the temporary file (and delete it again)
  shell: cat /tmp/ansible-new-users.txt && rm /tmp/ansible-new-users.txt
  changed_when: false
  register: new_users

- name: Force password change on next login
  shell: usermod -p "" {{item}} && chage -d 0 {{item}}
  changed_when: false
  with_items: new_users.stdout_lines
